xrandr --dpi 96 || true
xrandr --output HDMI-1 --mode 1920x1080 || true
xrandr --output HDMI-2 --mode 1920x1080 || true
xrandr --output HDMI-2 --same-as HDMI-1 --auto
xsetroot -solid black -xcf /usr/share/icons/whiteglass/cursors/left_ptr 48 &

xset -dpms
setterm -blank 0 -powerdown 0
xset s off

sleep infinity
