RIGHT_INTERFACE="eth0"
LEFT_INTERFACE="eth1"
THEME_COLOR="#33393b"
VERSION="v0.1"
GIT_VERSION="%%gitversion%%"

PUBLIC_NETNS_NAME="public"
NETNS_RIGHT_BRIDGE_NAME="right-br"

SERIAL_BUTTON="/dev/ttyACM0"
